// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SalaryInsights.Infrastructure;

#nullable disable

namespace SalaryInsights.Infrastructure.Migrations
{
    [DbContext(typeof(SalaryInsightsDbContext))]
    [Migration("20260302134655_CreateAuthProviderTables")]
    partial class CreateAuthProviderTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SalaryInsights.Domain.Models.AuthProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_type");

                    b.HasKey("Id");

                    b.HasIndex("ProviderType");

                    b.ToTable("auth_providers", (string)null);
                });

            modelBuilder.Entity("SalaryInsights.Domain.Models.AuthProviderSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthProviderId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsInitialized")
                        .HasColumnType("boolean")
                        .HasColumnName("is_initialized");

                    b.Property<string>("Setting")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings");

                    b.HasKey("Id");

                    b.HasIndex("AuthProviderId")
                        .IsUnique();

                    b.ToTable("auth_provider_settings", (string)null);
                });

            modelBuilder.Entity("SalaryInsights.Domain.Models.AuthProviderSetting", b =>
                {
                    b.HasOne("SalaryInsights.Domain.Models.AuthProvider", "AuthProvider")
                        .WithOne("ProviderSetting")
                        .HasForeignKey("SalaryInsights.Domain.Models.AuthProviderSetting", "AuthProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthProvider");
                });

            modelBuilder.Entity("SalaryInsights.Domain.Models.AuthProvider", b =>
                {
                    b.Navigation("ProviderSetting")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
