# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy container app to Azure

on:
  push:
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_9203886328f74cd0b5c075f508b9e33a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_aff680256ac541f6a3d8d28f82225e07 }}

    - name: Extract metadata (tags) for Docker
      id: meta
      run: echo ::set-output name=tags::${GITHUB_REF#refs/tags/v}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_9203886328f74cd0b5c075f508b9e33a }}/danvic712/salary-insights:${{ steps.meta.outputs.tags }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'salary-insights'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_90e0986b783b4c63b1bc01b37ccbdcd8 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_9203886328f74cd0b5c075f508b9e33a }}/danvic712/salary-insights:${{ steps.meta.outputs.tags }}'