name: Docker Image CI

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:

  Build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Extract metadata (tags) for Docker
      id: meta
      run: echo ::set-output name=tags::${GITHUB_REF#refs/tags/}
    
    - name: Build the Docker image
      run: docker build . -t danvic712/salary-insights:${{ steps.meta.outputs.tags }}
      working-directory: src/SalaryInsights